import React, { useState } from 'react';
import { Terminal, Copy, Check, FileText, Settings, Sparkles, Code2, AlertCircle } from 'lucide-react';
import { AutomationConfig } from '../types';

interface ScriptGeneratorProps {
  config: AutomationConfig;
  activeScenarioId: string;
}

export default function ScriptGenerator({ config, activeScenarioId }: ScriptGeneratorProps) {
  const [activeTab, setActiveTab] = useState<'maestro' | 'bash' | 'xctest'>('maestro');
  const [copied, setCopied] = useState(false);

  const triggerId = config.triggerButtonId || 'storekit_age_btn';
  const bundle = config.bundleId || 'com.gamestudio.legendquest';
  const appVersion = config.appVersion || 'v3.4.0-Beta';
  const tester = (config.testerName || 'tester').toLowerCase().replace(/\s+/g, '_');
  const dateStr = new Date().toISOString().split('T')[0];

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // 1. Maestro Flow Script (YML)
  const maestroScript = `appId: "${bundle}"
---
# -----------------------------------------------------------------------------
# Maestro Automated Test: Age Assurance ${activeScenarioId.toUpperCase()}
# Generated by: StoreKit Age Assurance Sandbox Workspace
# Target Device: ${config.deviceName || 'iPhone 15 Pro (Physical Device)'}
# -----------------------------------------------------------------------------

- clearState
- launchApp:
    arguments:
      -key: "STOREKIT_AGE_ASSURANCE_SCENARIO"
      -value: "${activeScenarioId}"

# Wait for application screen to fully load
- assertVisible: "Legend Quest"

# Start Recording Session via simulator CLI
- runScript: 
    commands:
      - "xcrun simctl io booted recordVideo --codec=h264 StoreKit_AgeAssurance_${activeScenarioId.toUpperCase()}_${tester}_${appVersion}_${dateStr}.mp4 & echo $! > record.pid"

# Trigger the Age Assurance Prompt in-app
- tapOn: "${triggerId}"

# Wait for native StoreKit Modal / Sheet to slide up
- assertVisible: "StoreKit Sandbox Age Sheet"
- takeScreenshot: "StoreKit_AgeAssurance_${activeScenarioId.toUpperCase()}_Prompt"

# Simulate selecting Sandbox response
- tapOn: "Simulate Apple Sandbox Response"

# Confirm compliance state is successfully enforced
- takeScreenshot: "StoreKit_AgeAssurance_${activeScenarioId.toUpperCase()}_Enforced"

# Stop Video Recording Session
- runScript:
    commands:
      - "kill $(cat record.pid) && rm record.pid"
`;

  // 2. Shell Command script for Xcode simulator CLI automation
  const bashScript = `#!/bin/bash
# -----------------------------------------------------------------------------
# StoreKit Age Assurance Automated Simulator Video Recorder
# Auto-generates and names recordings matching legal specifications
# -----------------------------------------------------------------------------

BUNDLE_ID="${bundle}"
TESTER="${tester}"
VERSION="${appVersion}"
DATE="${dateStr}"
SCENARIO="${activeScenarioId}"
OUTPUT_DIR="./Compliance_Recordings"

mkdir -p "$OUTPUT_DIR"

FILENAME="StoreKit_AgeAssurance_\${SCENARIO^^}_\${TESTER}_\${VERSION}_\${DATE}.mp4"
FILEPATH="$OUTPUT_DIR/$FILENAME"

echo "=========================================================="
echo "🎬 Starting Automated Age Assurance Test Video Capture"
echo "Scenario: $activeScenarioId"
echo "Output: $FILEPATH"
echo "=========================================================="

# 1. Start background simulator recording (non-blocking)
echo "🎥 Initializing simctl screen recorder..."
xcrun simctl io booted recordVideo --codec=h264 "$FILEPATH" &
RECORD_PID=$!

# Give the video recorder 1.5 seconds to warm up
sleep 1.5

# 2. Trigger the Deep Link to start the verification screen
echo "📱 Triggering app gateway with deep link..."
xcrun simctl openurl booted "legendquest://storekit-verify?scenario=$activeScenarioId"

echo "👉 Perform the simulator test steps now (Click Evaluate and Simulate response)."
echo "Press [ENTER] to stop recording and archive video..."
read -r

# 3. Terminate recording gracefully
echo "💾 Finalizing recording..."
kill -SIGINT $RECORD_PID
wait $RECORD_PID 2>/dev/null

echo "✅ Video captured & named successfully!"
echo "📂 Saved to: $FILEPATH"
`;

  // 3. Swift UI Test (XCTest) Generator
  const xctestScript = `import XCTest

class StoreKitAgeAssuranceTests: XCTestCase {
    let app = XCUIApplication()
    let scenario = "${activeScenarioId}"
    
    override func setUpWithError() throws {
        continueAfterFailure = false
        app.launchArguments.append("--storekit-age-assurance-scenario")
        app.launchArguments.append(scenario)
        app.launch()
    }
    
    func testAgeAssuranceFlow() throws {
        // Start Video Capture using Xcode Test Attachment
        let screen = XCUIScreen.main
        let attachment = XCTAttachment(screenshot: screen.screenshot())
        attachment.name = "Start_State_\\(scenario)"
        attachment.lifetime = .keepAlways
        add(attachment)
        
        // Tap trigger button
        let triggerButton = app.buttons["${triggerId}"]
        XCTAssertTrue(triggerButton.waitForExistence(timeout: 5))
        triggerButton.tap()
        
        // Wait for StoreKit Sandbox age sheet to slide up
        let sandboxSheet = app.otherElements["StoreKit Sandbox Age Sheet"]
        XCTAssertTrue(sandboxSheet.waitForExistence(timeout: 10))
        
        // Click simulation action
        let simulateButton = app.buttons["Simulate Apple Sandbox Response"]
        XCTAssertTrue(simulateButton.waitForExistence(timeout: 5))
        simulateButton.tap()
        
        // Attachment stores the final compliance outcome
        let finalAttachment = XCTAttachment(screenshot: screen.screenshot())
        finalAttachment.name = "StoreKit_AgeAssurance_\\(scenario.uppercased())_Outcome"
        finalAttachment.lifetime = .keepAlways
        add(finalAttachment)
    }
}`;

  const getActiveScriptText = () => {
    if (activeTab === 'maestro') return maestroScript;
    if (activeTab === 'bash') return bashScript;
    return xctestScript;
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200/80 shadow-sm p-6 flex flex-col">
      <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-100">
        <div>
          <h3 className="text-base font-bold text-slate-800 flex items-center gap-2">
            <Terminal className="w-5 h-5 text-blue-600" />
            Automated Testing Scripts
          </h3>
          <p className="text-xs text-slate-500">Generate automated test configs and video capture scripts</p>
        </div>
        <div className="flex bg-gray-100 p-1 rounded-xl">
          {(['maestro', 'bash', 'xctest'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg capitalize transition-all ${
                activeTab === tab 
                  ? 'bg-white text-blue-700 shadow-sm' 
                  : 'text-gray-600 hover:text-gray-950'
              }`}
            >
              {tab === 'xctest' ? 'XCUI Test' : tab === 'bash' ? 'Bash Utility' : 'Maestro'}
            </button>
          ))}
        </div>
      </div>

      {/* Script Explainer Alert */}
      <div className="mb-4 p-3 bg-blue-50/30 rounded-xl border border-blue-100/40 flex items-start gap-2.5">
        <Sparkles className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
        <div className="text-[11px] text-slate-700 leading-relaxed">
          {activeTab === 'maestro' && "Maestro is a declarative mobile UI automation tool. This configuration automatically runs, injects sandbox arguments, triggers native sheets, takes screenshots, and captures perfectly-named videos."}
          {activeTab === 'bash' && "Runs directly on your Mac terminal. It boots background recording via simctl, invokes deep-links to launch the app, lets you carry out the manual steps, and automatically stops and saves the video with precise naming."}
          {activeTab === 'xctest' && "Native iOS UI Test script using Apple's XCTest framework. Inject this into your Xcode workspace to automate assertion flows and capture screenshots automatically during test runs."}
        </div>
      </div>

      {/* Script Source Preview Codeblock */}
      <div className="relative flex-1 min-h-[300px] bg-slate-900 rounded-xl overflow-hidden border border-slate-800 flex flex-col">
        {/* Terminal Header */}
        <div className="flex items-center justify-between px-4 py-2 bg-slate-950 border-b border-slate-800/80">
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 bg-red-500/80 rounded-full"></span>
            <span className="w-3 h-3 bg-yellow-500/80 rounded-full"></span>
            <span className="w-3 h-3 bg-emerald-500/80 rounded-full"></span>
            <span className="text-[10px] font-mono text-slate-400 ml-2">
              {activeTab === 'maestro' ? 'storekit_age_assurance.yaml' : activeTab === 'bash' ? 'record_assurance_scenario.sh' : 'StoreKitAgeAssuranceTests.swift'}
            </span>
          </div>
          <button
            onClick={() => handleCopy(getActiveScriptText())}
            className="flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-semibold text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-md transition-all active:scale-95"
          >
            {copied ? (
              <>
                <Check className="w-3 h-3 text-emerald-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-3 h-3" />
                Copy Script
              </>
            )}
          </button>
        </div>

        {/* Code Content */}
        <pre className="flex-1 overflow-auto p-4 text-[11px] font-mono text-slate-300 leading-relaxed select-all">
          <code>{getActiveScriptText()}</code>
        </pre>
      </div>

      {/* Local Video Recording Tips */}
      <div className="mt-4 p-3 bg-amber-50/50 rounded-xl border border-amber-100/50 flex items-start gap-2">
        <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
        <div className="text-[10px] text-amber-900 leading-normal">
          <strong>Tip on Simulator Video Recording:</strong> When using Xcode Simulators, you can record the screen from your Mac terminal at any time using: <code className="bg-white px-1.5 py-0.5 rounded border border-amber-200 font-mono text-[9px]">xcrun simctl io booted recordVideo output.mp4</code>. Press <code className="bg-white px-1.5 py-0.5 rounded border border-amber-200 font-mono text-[9px]">Ctrl+C</code> in the terminal to stop.
        </div>
      </div>
    </div>
  );
}
